name: Build STLs
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install openscad
      - run: make
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Zelti STLs
          files: '*.stl'
permissions:
  contents: write
